BrightspaceUI/labs

src/controllers/computed-values/README.md, src/controllers/computed-values/computed-values.js
This change will allow custom controllers to be used within the ComputedValues array of controllers. This is needed in order to be able to control the order of execution of compute methods between custom controllers and any other controllers within the ComputedValues controller.
=> feat: add support for custom controllers within the ComputedValues controller

src/controllers/computed-values/computed-value.js
Found a small issue with custom implementations of `shouldCompute`.
After every run of `shouldCompute`, the `ComputeValue` class stores the `currDependencies` so they can be the `prevDependencies` the next time this runs. However, if `shouldCompute` returned `false`, the class was making the assumption that the dependencies hadn't changed, so there was no need to store the `currDependencies` for next time. This is true when using the default implementation of `shouldCompute`, but that's not always the case if you were to implement a custom `shouldCompute` function.
The logic here is now being updated so that `currDependencies` is always stored for the next run regardless of whatever `shouldCompute` returns so that checks for changes are accurate to every update.
Note that a quick search …
=> Always update prevDeps even if shouldCompute returns false

.github/workflows/update-package-lock.yml, CODEOWNERS
Adding github action to run update-package-lock based on the following guide: https://desire2learn.atlassian.net/wiki/spaces/DEVCENTRAL/pages/3643179788/How+to+track+and+manage+JavaScript+dependencies+with+package-lock.json#What-should-I-do%3F
This is currently set up to run Mon-Fri 7:30am EST. Let me know if you think this should be at a different time or less frequent.
Will do some testing once merged to make sure it works as expected.
=> Set up update-package-lock github action

.github/workflows/ci.yml, .github/workflows/visual-diff.yml, README.md, package-lock.json, package.json
Remove lit-analyzer as suggested in https://github.com/BrightspaceUI/labs/pull/43#issuecomment-1579481332.
Update CI to use npm ci instead of npm install.
Move playwright runner installation into dev dependencies instead of being part of CI.
=> Remove lit-analyzer and use npm ci in pipelines

.github/dependabot.yml, package-lock.json, package.json
Noticed this dependabot config wasn't cleaned up after the Lit 2 migration. Getting it more up-to-date until we switch to our testing library
=> Cleanup dependabot config and package.json

demo/components/opt-in-flyout/index.html, src/components/opt-in-flyout/README.md, src/components/opt-in-flyout/flyout-impl.js, src/components/opt-in-flyout/opt-in-flyout.js, src/components/opt-in-flyout/opt-out-flyout.js, test/components/opt-in-flyout/opt-in-flyout.test.js, test/components/opt-in-flyout/opt-out-flyout.test.js
While writing the vdiff tests, I noticed that because the attribute is named "title", the flyouts get a permanent browser tooltip whenever you hover over anywhere within the flyout. So this renamed that to `flyout-title` similar to how collapsible panel works.
Since we're dealing with breaking changes anyway, I also renamed `open` -> `opened` to match our dialogs.
=> rename title -> flyout-title and open -> opened

src/components/opt-in-flyout/README.md, src/components/opt-in-flyout/flyout-impl.js, src/components/opt-in-flyout/opt-in-flyout.js, src/components/opt-in-flyout/opt-out-flyout.js
Another thing I noticed while writing vdiff tests. This `tab-position` property was used to control where the flyout "tab" goes -- it defaults to the right of the screen but can be positioned on the left, the centre or a custom value can be provided. Nothing was setting this, so I'm removing it to simplify the code.
=> fix: remove tab-position

src/components/opt-in-flyout/opt-out-dialog.js, src/components/opt-in-flyout/opt-out-reason-selector.js, test/components/opt-in-flyout/opt-in-flyout.test.js, test/components/opt-in-flyout/opt-out-dialog.test.js
If this is meant to act as an example, I figured I should add some accessibility tests. They found a missing label on a `<select>`. There's a bunch of other weird `<label>` stuff going on here, and they don't match our actual for label styles, but I think I'm going to draw the line here to limit visual changes.
=> fix: add a11y tests and fix select label

test/components/checkbox-drawer/checkbox-drawer.test.js, test/components/pagination/pager-numeric.test.js
This repo uses `@brightspace-ui/testing`, so it can just get `runConstructor` from there. Someday, we'll want to remove the one in `core`.
=> Remove constructor-test-helper reference

.github/workflows/ci.yml, README.md, d2l-test-reporting.config.json, package.json, test/components/checkbox-drawer/checkbox-drawer.axe.js, test/components/checkbox-drawer/checkbox-drawer.test.js, test/components/opt-in-flyout/opt-in-flyout.axe.js, test/components/opt-in-flyout/opt-in-flyout.test.js, test/components/opt-in-flyout/opt-out-dialog.axe.js, test/components/opt-in-flyout/opt-out-dialog.test.js, test/components/pagination/pager-numeric.axe.js, test/components/pagination/pager-numeric.test.js
I'm hoping eventually to find a better way to do this so we can track at the test level but based on the current test reporting implementation this is the easiest way to track them separately from just standard old unit tests.
=> Split out axe tests for better tracking

d2l-test-runner.config.js, package-lock.json
The default is to generate the report in CI now.
=> Update to latest `@brightspace-ui/testing`

demo/components/view-toggle/index.html, index.html, package.json, src/components/view-toggle/README.md, src/components/view-toggle/view-toggle.js, test/components/view-toggle/view-toggle.axe.js, test/components/view-toggle/view-toggle.test.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7241)
=> feat: migrate d2l-labs-view-toggle

src/components/attribute-picker/README.md
[Oscar pointed out](https://github.com/Brightspace/manager-view-fra/pull/2887#pullrequestreview-2500795534) that I'd forgotten to include the `label` property in the documentation, so I'm adding that in now!
=> Add missing label to attribute-picker docn

demo/utilities/reactive-store/basic-demo.js, demo/utilities/reactive-store/context-demo.js, demo/utilities/reactive-store/index.html, demo/utilities/reactive-store/multiple-consumers-demo.js, demo/utilities/reactive-store/my-store.js, src/utilities/reactive-store/README.md, src/utilities/reactive-store/context-controllers.js, src/utilities/reactive-store/store-consumer.js, src/utilities/reactive-store/store-reactor.js, test/utilities/reactive-store/context-controllers.test.js, test/utilities/reactive-store/store-consumer.test.js
This change makes it so the `StoreConsumer` and the context `Provider`/`Consumer` pair are instantiated as proxies for the store they're connecting to.
This makes it possible for all methods and properties defined within the store (not just ones defined in the static `properties`) to be accessed and used from any consumer.
Did this work as part of this refactor: https://desire2learn.atlassian.net/browse/MED-1354
=> feat: Switch to using proxies for reactive store consumers

src/utilities/reactive-store/reactive-store.js, test/utilities/reactive-store/reactive-store.test.js
This fixes an issue with the original implementation that made it so extending a previously defined ReactiveStore and implementing new reactive properties would override any previous reactive properties. With this fix, properties inherited from ancestors will be implemented before descendants.
=> MED-1431 Make sure the ReactiveStore supports reactive property inheritance

src/utilities/reactive-store/constants.js, src/utilities/reactive-store/context-controllers.js, src/utilities/reactive-store/reactive-store.js, src/utilities/reactive-store/store-consumer.js, src/utilities/reactive-store/store-reactor.js, test/utilities/reactive-store/store-consumer.test.js
Related to https://github.com/BrightspaceUI/labs/pull/549
I missed applying the same fix to the `changedProperties` initialization process.
=> MED-1431 Support inherited properties when initializing changedProperties

demo/components/navigation/button-link.html, src/components/navigation/navigation-dropdown-button-custom.js, src/components/navigation/navigation-skip.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7686)
Adding the void `href` on navigation-skip makes the anchor dispatch click events for keyboard. It also announces the anchor as a link which it was not doing before. 
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7688)
Adding label properties to add them to the underlying button instead of the custom opener component. NVDA does not seem to like the custom component having labels or ids(no idea why the latter is the case).
=> fix: accessibility issues with navigation

CODEOWNERS
Align this to match [`core`'s `CODEOWNERS` file](https://github.com/BrightspaceUI/core/blob/e4726cdab1f942e0af171e808c43f7435a3a9540/.github/CODEOWNERS).
=> GAUD-7818 - Update CODEOWNERS

src/components/media-player/media-player.js, src/components/media-player/slider-bar.js
This is only used by the media-player - just updating the name to match the rest of the repo.
=> GAUD-7905 - Rename slider-bar

src/components/grade-result/README.md, src/components/grade-result/grade-result-letter-score.js, src/components/grade-result/grade-result-numeric-score.js, src/components/grade-result/grade-result-presentational.js
Cleaning up the README to create a nicer page for the Daylight site.
I moved a lot of the README contents into the files in case we ever decide to hook up `labs` to create the `custom-elements.json` files. But I can revert that part if we want and just leave it in the README only.
=> GAUD-7947 - Cleanup grade-result docs

src/components/accordion/accordion-collapse.js
https://desire2learn.atlassian.net/browse/PHNX-2820
The first time you navigate to the content page in Sequence Launcher,  the first accordion menu item is opened by default, but the `_state` attribute of the `d2l-labs-accordion-collapse` element is set to `closed`.
The `_state` of the first item should be set to `opened`.
This is done by checking by checking if the item has been `opened`. In `connectedCallback` (which runs when the element is connected to the DOM), we set the `_state` to `'open'` if this is the case. This ensures the item's `_state` is set correctly.
[PHNX-2820]: https://desire2learn.atlassian.net/browse/PHNX-2820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PHNX-2820 Ensure Accordion Initial State Accuracy

demo/utilities/router/route-loader.js, src/utilities/router/README.md, src/utilities/router/router.js, test/utilities/router/router.test.js
We'd prefer that the route order fix be applied by default so that consumers don't need to worry about it, we don't need to warn them about it and we can generally move on with our lives. 😆 
I'm going to do this in 4 phases:
1. Introduce `disableRouteOrderFix` (complete ✅ ). When set to `true`, the fix won't be applied. It defaults to `false`.
2. Update consumers that aren't currently setting `enableRouteOrderFix` to pass `disableRouteOrderFix` (complete ✅ ).
3. Remove the concept of a `enableRouteOrderFix` option, so the fix will be enabled by default (this PR)
4. Update consumers that were sending `enableRouteOrderFix` to no longer pass it.
=> GAUD-8160: remove enablerRouteOrderFix option

demo/components/grade-result/index.html, src/components/grade-result/README.md, src/components/grade-result/grade-result-icon-button.js, src/components/grade-result/grade-result-letter-score.js, src/components/grade-result/grade-result-presentational.js, test/components/grade-result/d2l-grade-result-autograde-provided.vdiff.js, test/components/grade-result/d2l-grade-result-custom-manual-override-text.vdiff.js, test/components/grade-result/d2l-grade-result-presentational.test.js, test/components/grade-result/d2l-grade-result-read-only.vdiff.js, test/components/grade-result/d2l-grade-result-student-grade-preview.vdiff.js, test/components/grade-result/d2l-grade-result-write-enabled.vdiff.js
Many of the `<d2l-labs-grade-result-*>` components don't adhere to our kebab-case guidance for multi-word attributes, and we want to resolve that.
This change is going to happen in 3 stages:
1. Go through consumers of the components and add both kebab-case and non-kebab-case attributes (complete ✅)
2. Switch the `<d2l-labs-grade-result-*>` components to only support kebab-case (this PR)
3. Go back through consumers and remove the non-kebab-case attributes
=> GAUD-8027: switch to kebab-case attributes

demo/utilities/router/app.js
`d2l-menu-item-link` now works with the router (https://github.com/BrightspaceUI/core/pull/6016). Used these changes for testing - adding menu-item-links to the router demo.
=> GAUD-8369 - Add menu-item-links to router demo

demo/utilities/router/route-loader.js, src/utilities/router/router.js, test/utilities/router/router.test.js
This allows us to use the loader as a means of loading other kinds of data other than just js modules. e.g.
``` javascript
registerRoutes([
{
pattern: '/d2l/ap/InsightsPortal/:orgUnitId/:tab',
loader: async(ctx) => {
const importPromise = import('./app.js');
const dataPromise = (async() => {
const result = await fetch('/need/more/data');
ctx.loaderData= await result.json();
})();
await Promise.all([dataPromise, importPromise]);
},
view: ({ loaderData}) => html`<d2l-my-app .loaderData=${options.loaderData}></d2l-my-app>`
}
], {});
```
=> NTNGL-4224 | Loader can access Context

src/components/media-player/media-player.js
https://desire2learn.atlassian.net/browse/MED-1881
* Adds support for new timeline thumbnails file name (e.g. `timelineThumbnails-h90w160i60-hash.png`)
* This is dependent on the coming changes from this PR: https://github.com/Brightspace/d2l-content-service/pull/2917
=> MED-1881 Add support for new timeline thumbnails file name
